using Azure.Core;
using CdIts.Npgsql.AadExtensions;
using FluentAssertions;
using Moq;
using Npgsql;

namespace Tests;

public class Tests
{
    [Test]
    public void TestManagedIdentity()
    {
        var mock = new Mock<TokenCredential>();
        mock.Setup(c => c.GetTokenAsync(It.IsAny<TokenRequestContext>(), It.IsAny<CancellationToken>())).ReturnsAsync(
            new AccessToken("eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiJodHRwczovL29zc3JkYm1zLWFhZC5kYXRhYmFzZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzA2ZWM2ZDVjLTBkZmYtNGVkZi1hNDJmLTYxNDE5MzNjMDZhYy8iLCJpYXQiOjE2NzE2MzM5NDYsIm5iZiI6MTY3MTYzMzk0NiwiZXhwIjoxNjcxNzIwNjQ2LCJhaW8iOiJFMlpnWUdpN3ZFN2t1dVRPNXVzUlo4NVZTOTJPQUFBPSIsImFwcGlkIjoiZmJhM2NhOGEtY2Y2Ny00YTRmLTk5OTgtMjM1ZWU4ODFiYjkxIiwiYXBwaWRhY3IiOiIyIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMDZlYzZkNWMtMGRmZi00ZWRmLWE0MmYtNjE0MTkzM2MwNmFjLyIsIm9pZCI6IjAxMmJhODE2LTg1MTQtNDliNS1iY2NiLTBjNDY3ODJmNjQ4ZSIsInJoIjoiMC5BWUlBWEczc0J2OE4zMDZrTDJGQmt6d0dyRkRZUEJMZjJiMUFsTlhKOEh0X29nT1ZBQUEuIiwic3ViIjoiMDEyYmE4MTYtODUxNC00OWI1LWJjY2ItMGM0Njc4MmY2NDhlIiwidGlkIjoiMDZlYzZkNWMtMGRmZi00ZWRmLWE0MmYtNjE0MTkzM2MwNmFjIiwidXRpIjoidjh6c05FV0FkMEdBX290bGx4UVBBZyIsInZlciI6IjEuMCJ9.nmTc84zZVSAFvk_5iy4E1ORtemSywHF2NalLYKzvnB2q9N1Wnu_aUrr82Rio1dLPgZAqq1SkoLmjteoPX7xnj-ClBv2HvYL5GZyOjK4aYu77e0HBy_oEC6JZL_35-liRLpz4c7aJt5dW4QGhbTfdL4XozGClgrxiqftXgzQeH-O_MDvsEV9NqMRKZ6x0DzwbioMzP6-0uwoVppIe9_dFOu6wan6J1CGxMSXWhWKY-YOTuSK3Do5mWOWRdKw4_oH028C-V7xRHS9wKzvOSlWY7UAZg2U3RevXme1IH9MVf8890gMgjPVgAvWzY-OqYSzz-RLQihgHtDMHmhwomF2YeA", DateTimeOffset.UtcNow));
        var builder = new NpgsqlDataSourceBuilder();
        builder.UseAadUserFromToken(mock.Object).Should().BeTrue();
        builder.ConnectionStringBuilder.Username.Should().Be("012ba816-8514-49b5-bccb-0c46782f648e");
    }
    
    [Test]
    public void TestManagedIdentityOid()
    {
        var mock = new Mock<TokenCredential>();
        mock.Setup(c => c.GetTokenAsync(It.IsAny<TokenRequestContext>(), It.IsAny<CancellationToken>())).ReturnsAsync(
            new AccessToken("eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiJodHRwczovL29zc3JkYm1zLWFhZC5kYXRhYmFzZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzA2ZWM2ZDVjLTBkZmYtNGVkZi1hNDJmLTYxNDE5MzNjMDZhYy8iLCJpYXQiOjE2NzE2MzM5NDYsIm5iZiI6MTY3MTYzMzk0NiwiZXhwIjoxNjcxNzIwNjQ2LCJhaW8iOiJFMlpnWUdpN3ZFN2t1dVRPNXVzUlo4NVZTOTJPQUFBPSIsImFwcGlkIjoiZmJhM2NhOGEtY2Y2Ny00YTRmLTk5OTgtMjM1ZWU4ODFiYjkxIiwiYXBwaWRhY3IiOiIyIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMDZlYzZkNWMtMGRmZi00ZWRmLWE0MmYtNjE0MTkzM2MwNmFjLyIsIm9pZCI6IjAxMmJhODE2LTg1MTQtNDliNS1iY2NiLTBjNDY3ODJmNjQ4ZSIsInJoIjoiMC5BWUlBWEczc0J2OE4zMDZrTDJGQmt6d0dyRkRZUEJMZjJiMUFsTlhKOEh0X29nT1ZBQUEuIiwic3ViIjoiMDEyYmE4MTYtODUxNC00OWI1LWJjY2ItMGM0Njc4MmY2NDhlIiwidGlkIjoiMDZlYzZkNWMtMGRmZi00ZWRmLWE0MmYtNjE0MTkzM2MwNmFjIiwidXRpIjoidjh6c05FV0FkMEdBX290bGx4UVBBZyIsInZlciI6IjEuMCJ9.nmTc84zZVSAFvk_5iy4E1ORtemSywHF2NalLYKzvnB2q9N1Wnu_aUrr82Rio1dLPgZAqq1SkoLmjteoPX7xnj-ClBv2HvYL5GZyOjK4aYu77e0HBy_oEC6JZL_35-liRLpz4c7aJt5dW4QGhbTfdL4XozGClgrxiqftXgzQeH-O_MDvsEV9NqMRKZ6x0DzwbioMzP6-0uwoVppIe9_dFOu6wan6J1CGxMSXWhWKY-YOTuSK3Do5mWOWRdKw4_oH028C-V7xRHS9wKzvOSlWY7UAZg2U3RevXme1IH9MVf8890gMgjPVgAvWzY-OqYSzz-RLQihgHtDMHmhwomF2YeA", DateTimeOffset.UtcNow));
        var builder = new NpgsqlDataSourceBuilder();
        builder.UseAadUserFromToken(mock.Object, new []{"oid"}).Should().BeTrue();
        builder.ConnectionStringBuilder.Username.Should().Be("012ba816-8514-49b5-bccb-0c46782f648e");
    }
    
    [Test]
    public void TestCliUser()
    {
        var mock = new Mock<TokenCredential>();
        mock.Setup(c => c.GetTokenAsync(It.IsAny<TokenRequestContext>(), It.IsAny<CancellationToken>())).ReturnsAsync(
            new AccessToken("eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL29zc3JkYm1zLWFhZC5kYXRhYmFzZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2VkY2I2Nzc3LTk2MTItNDExNS05Mjc3LWUyMWRlMWYyODRjMy8iLCJpYXQiOjE2NzE2MzU3MjAsIm5iZiI6MTY3MTYzNTcyMCwiZXhwIjoxNjcxNjQwODE1LCJhY3IiOiIxIiwiYWlvIjoiQVhRQWkvOFRBQUFBMlFGTlVrY0N6SEpvSVBlUmloVERIV0R4ODRMdXlsekhEVGMwbkI4UllUOE1NaWFMYnVGekxOQUU3Wmh0cnlsekFpRUU1dE1wM1ExdDI3cTZVV2ZKMHUvdlprK3NmOVVSMjN2enBXcWNGaXljVHJ3VXFGYllKdlpnYkREZGdmaTZTQUhOMnEyT0EyaGhrblJOV2EwN213PT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJEaWVkZXJpY2hzIiwiZ2l2ZW5fbmFtZSI6IkNsYWFzIiwiZ3JvdXBzIjpbIjM4Yjg1MjVkLWJlYWUtNGU3MS04YjlmLWQ2ZDA1MjUzMjQ4NiIsImRkYTY1NzBhLTg4ZmQtNGU2Ni1hMjI1LTE5MDM4YjRkZTMwYiIsImNkMjZlMmNmLTljYTgtNDZiMi05ZWZkLWYzNDYxODc4ZTgzMiJdLCJpcGFkZHIiOiI5NS4zMy4xNTIuMTk2IiwibmFtZSI6IkNsYWFzIERpZWRlcmljaHMiLCJvaWQiOiJmZjIyNjRiZi0xZWZmLTQ1MWUtOWM0MC01NWIyMWM4NzQ2NGMiLCJwdWlkIjoiMTAwMzIwMDE0NTZFRTA2MSIsInJoIjoiMC5BWUVBZDJmTDdSS1dGVUdTZC1JZDRmS0V3MURZUEJMZjJiMUFsTlhKOEh0X29nT0JBRHcuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiMDYweWtxenh5NmJHOUlSdkJwd0ZyRENsQW8tVUlqY0hQSDJsaWJtVFktTSIsInRpZCI6ImVkY2I2Nzc3LTk2MTItNDExNS05Mjc3LWUyMWRlMWYyODRjMyIsInVuaXF1ZV9uYW1lIjoiY2xhYXMuZGllZGVyaWNoc0BjZC1pdHMuZGUiLCJ1cG4iOiJjbGFhcy5kaWVkZXJpY2hzQGNkLWl0cy5kZSIsInV0aSI6Inl4djEzWmdRWEVpeUJzUjRMc21HQUEiLCJ2ZXIiOiIxLjAifQ.PYShdYWSwyfdHH6axGcqXtON27JN_2YsleTtWaotr0pMYVDeyElK__A999vEIVYa5qOM5DWS8Zvb9JJBmNXxUg79ebSJCebvMFM7UkAQ2sYflrmGV5Fpyo61tnk2K-zRM2kNS0b8FMK2jX2VCxVhosbevaa8zcywPeuYiXaK23eG2-2m67mkw32IsZ-FWk4ZYHmyMZPVTcxGm8qZN2ZqiLPd60Tz2SJUDLmM1Ey57naRe9fdlLCPVF_0h2p9YNfeNaOfuYmcGMuZUiQbkwUWYbQWr9MTwAvQPsl3vJwillc7HNLyktPaOjCl7aF4Z_U_KQNXO24DXTJF9u1SFSGdDw", DateTimeOffset.UtcNow));
        var builder = new NpgsqlDataSourceBuilder();
        builder.UseAadUserFromToken(mock.Object).Should().BeTrue();
        builder.ConnectionStringBuilder.Username.Should().Be("claas.diederichs@cd-its.de");
    }
    
    [Test]
    public void TestCliUserObjectId()
    {
        var mock = new Mock<TokenCredential>();
        mock.Setup(c => c.GetTokenAsync(It.IsAny<TokenRequestContext>(), It.IsAny<CancellationToken>())).ReturnsAsync(
            new AccessToken("eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL29zc3JkYm1zLWFhZC5kYXRhYmFzZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2VkY2I2Nzc3LTk2MTItNDExNS05Mjc3LWUyMWRlMWYyODRjMy8iLCJpYXQiOjE2NzE2MzU3MjAsIm5iZiI6MTY3MTYzNTcyMCwiZXhwIjoxNjcxNjQwODE1LCJhY3IiOiIxIiwiYWlvIjoiQVhRQWkvOFRBQUFBMlFGTlVrY0N6SEpvSVBlUmloVERIV0R4ODRMdXlsekhEVGMwbkI4UllUOE1NaWFMYnVGekxOQUU3Wmh0cnlsekFpRUU1dE1wM1ExdDI3cTZVV2ZKMHUvdlprK3NmOVVSMjN2enBXcWNGaXljVHJ3VXFGYllKdlpnYkREZGdmaTZTQUhOMnEyT0EyaGhrblJOV2EwN213PT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJEaWVkZXJpY2hzIiwiZ2l2ZW5fbmFtZSI6IkNsYWFzIiwiZ3JvdXBzIjpbIjM4Yjg1MjVkLWJlYWUtNGU3MS04YjlmLWQ2ZDA1MjUzMjQ4NiIsImRkYTY1NzBhLTg4ZmQtNGU2Ni1hMjI1LTE5MDM4YjRkZTMwYiIsImNkMjZlMmNmLTljYTgtNDZiMi05ZWZkLWYzNDYxODc4ZTgzMiJdLCJpcGFkZHIiOiI5NS4zMy4xNTIuMTk2IiwibmFtZSI6IkNsYWFzIERpZWRlcmljaHMiLCJvaWQiOiJmZjIyNjRiZi0xZWZmLTQ1MWUtOWM0MC01NWIyMWM4NzQ2NGMiLCJwdWlkIjoiMTAwMzIwMDE0NTZFRTA2MSIsInJoIjoiMC5BWUVBZDJmTDdSS1dGVUdTZC1JZDRmS0V3MURZUEJMZjJiMUFsTlhKOEh0X29nT0JBRHcuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiMDYweWtxenh5NmJHOUlSdkJwd0ZyRENsQW8tVUlqY0hQSDJsaWJtVFktTSIsInRpZCI6ImVkY2I2Nzc3LTk2MTItNDExNS05Mjc3LWUyMWRlMWYyODRjMyIsInVuaXF1ZV9uYW1lIjoiY2xhYXMuZGllZGVyaWNoc0BjZC1pdHMuZGUiLCJ1cG4iOiJjbGFhcy5kaWVkZXJpY2hzQGNkLWl0cy5kZSIsInV0aSI6Inl4djEzWmdRWEVpeUJzUjRMc21HQUEiLCJ2ZXIiOiIxLjAifQ.PYShdYWSwyfdHH6axGcqXtON27JN_2YsleTtWaotr0pMYVDeyElK__A999vEIVYa5qOM5DWS8Zvb9JJBmNXxUg79ebSJCebvMFM7UkAQ2sYflrmGV5Fpyo61tnk2K-zRM2kNS0b8FMK2jX2VCxVhosbevaa8zcywPeuYiXaK23eG2-2m67mkw32IsZ-FWk4ZYHmyMZPVTcxGm8qZN2ZqiLPd60Tz2SJUDLmM1Ey57naRe9fdlLCPVF_0h2p9YNfeNaOfuYmcGMuZUiQbkwUWYbQWr9MTwAvQPsl3vJwillc7HNLyktPaOjCl7aF4Z_U_KQNXO24DXTJF9u1SFSGdDw", DateTimeOffset.UtcNow));
        var builder = new NpgsqlDataSourceBuilder();
        builder.UseAadUserFromToken(mock.Object, new []{"oid"}).Should().BeTrue();
        builder.ConnectionStringBuilder.Username.Should().Be("ff2264bf-1eff-451e-9c40-55b21c87464c");
    }
    
    [Test]
    public void TestInvalidClaim()
    {
        var mock = new Mock<TokenCredential>();
        mock.Setup(c => c.GetTokenAsync(It.IsAny<TokenRequestContext>(), It.IsAny<CancellationToken>())).ReturnsAsync(
            new AccessToken("eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL29zc3JkYm1zLWFhZC5kYXRhYmFzZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2VkY2I2Nzc3LTk2MTItNDExNS05Mjc3LWUyMWRlMWYyODRjMy8iLCJpYXQiOjE2NzE2MzU3MjAsIm5iZiI6MTY3MTYzNTcyMCwiZXhwIjoxNjcxNjQwODE1LCJhY3IiOiIxIiwiYWlvIjoiQVhRQWkvOFRBQUFBMlFGTlVrY0N6SEpvSVBlUmloVERIV0R4ODRMdXlsekhEVGMwbkI4UllUOE1NaWFMYnVGekxOQUU3Wmh0cnlsekFpRUU1dE1wM1ExdDI3cTZVV2ZKMHUvdlprK3NmOVVSMjN2enBXcWNGaXljVHJ3VXFGYllKdlpnYkREZGdmaTZTQUhOMnEyT0EyaGhrblJOV2EwN213PT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJEaWVkZXJpY2hzIiwiZ2l2ZW5fbmFtZSI6IkNsYWFzIiwiZ3JvdXBzIjpbIjM4Yjg1MjVkLWJlYWUtNGU3MS04YjlmLWQ2ZDA1MjUzMjQ4NiIsImRkYTY1NzBhLTg4ZmQtNGU2Ni1hMjI1LTE5MDM4YjRkZTMwYiIsImNkMjZlMmNmLTljYTgtNDZiMi05ZWZkLWYzNDYxODc4ZTgzMiJdLCJpcGFkZHIiOiI5NS4zMy4xNTIuMTk2IiwibmFtZSI6IkNsYWFzIERpZWRlcmljaHMiLCJvaWQiOiJmZjIyNjRiZi0xZWZmLTQ1MWUtOWM0MC01NWIyMWM4NzQ2NGMiLCJwdWlkIjoiMTAwMzIwMDE0NTZFRTA2MSIsInJoIjoiMC5BWUVBZDJmTDdSS1dGVUdTZC1JZDRmS0V3MURZUEJMZjJiMUFsTlhKOEh0X29nT0JBRHcuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiMDYweWtxenh5NmJHOUlSdkJwd0ZyRENsQW8tVUlqY0hQSDJsaWJtVFktTSIsInRpZCI6ImVkY2I2Nzc3LTk2MTItNDExNS05Mjc3LWUyMWRlMWYyODRjMyIsInVuaXF1ZV9uYW1lIjoiY2xhYXMuZGllZGVyaWNoc0BjZC1pdHMuZGUiLCJ1cG4iOiJjbGFhcy5kaWVkZXJpY2hzQGNkLWl0cy5kZSIsInV0aSI6Inl4djEzWmdRWEVpeUJzUjRMc21HQUEiLCJ2ZXIiOiIxLjAifQ.PYShdYWSwyfdHH6axGcqXtON27JN_2YsleTtWaotr0pMYVDeyElK__A999vEIVYa5qOM5DWS8Zvb9JJBmNXxUg79ebSJCebvMFM7UkAQ2sYflrmGV5Fpyo61tnk2K-zRM2kNS0b8FMK2jX2VCxVhosbevaa8zcywPeuYiXaK23eG2-2m67mkw32IsZ-FWk4ZYHmyMZPVTcxGm8qZN2ZqiLPd60Tz2SJUDLmM1Ey57naRe9fdlLCPVF_0h2p9YNfeNaOfuYmcGMuZUiQbkwUWYbQWr9MTwAvQPsl3vJwillc7HNLyktPaOjCl7aF4Z_U_KQNXO24DXTJF9u1SFSGdDw", DateTimeOffset.UtcNow));
        var builder = new NpgsqlDataSourceBuilder();
        builder.UseAadUserFromToken(mock.Object, new []{"full_name"}).Should().BeFalse();
        builder.ConnectionStringBuilder.Username.Should().BeNull();
    }
}
